### ISSUE TITLE
"uration" inside a string gets highlighted

### ISSUE THREAD

**Issue by moll** [cmcaine/vim-uci#1]
Hey,

Dunno why, but the default OpenVPN config gets weird highlighting around `uration`:

```
config openvpn_recipe server_tun
    option _description     "Server configuration for a routed multi-client VPN"
    option _role            "server"
```

Syntax-wise it gets `uciConfigName`. Probably shouldn't.

**Comment by cmcaine** [comment]
Thanks for raising the issue. I've committed a change back to master that solves this.

**Comment by cmcaine** [comment]
(And the reason is that the look behind match was matching the text after "config". I've changed it to only match the text after "config " and also set a highlight group for strings).
