### ISSUE TITLE
[feature] content detect

### ISSUE THREAD

**Issue by Freed-Wu** [cmcaine/vim-uci#3]
As https://github.com/vim/vim/pull/14385, the reviewer of vim runtime hope it can add a content detection.

I open the discussion to see how can we add it.

Change the discussion to upstream to avoid disturb the reviewer of vim runtime.

TIA!

**Comment by cmcaine** [comment]
Relevant comment thread: https://github.com/vim/vim/pull/14385#discussion_r1558878741

The idea is to match files that have the right path and also the file content starts with the word "config". Supposedly dist/ft.vim has code that does similar stuff for other filetypes.

The existing detection is good enough for me and I don't really want to spend time implementing this. I am willing to review a PR that adds this behaviour.

@Freed-Wu, unrelated, but could you open a PR that adds the relevant parts of https://github.com/vim/vim/pull/14385 to this plugin? I'm thinking of the did_uci stuff. I don't know which parts should be here and which bits are specific to stuff that's bundled with the vim runtime.

**Comment by cmcaine** [comment]
Resolved with `s:detect_uci_statements()` https://github.com/cmcaine/vim-uci/blob/a5ca9af46c3f04c60dc4c7ce8679dc5145a0d24a/ftdetect/uci.vim
